version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - '51214:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gymdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

environment:
  -DATABASE_URL=postgresql://postgres:admin:51214@db:5432/gymdb # This is the database connection string used by Prisma